# Generated by Django 3.1.7 on 2021-06-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entertainmentdb',
            new_name='Newsdb',
        ),
    ]
