# Generated by Django 3.1.7 on 2021-06-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologyreview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveVideo_technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('nameofvideo', models.CharField(max_length=200)),
                ('videoPublicId', models.CharField(max_length=1000)),
                ('videoUrl', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
