# Generated by Django 3.1.7 on 2021-06-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologyreview', '0002_savevideo_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savevideo_technology',
            name='nameofvideo',
        ),
    ]
