# Generated by Django 3.1.7 on 2021-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entertainmentNewsdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('nextrandom', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='entertainmentSaveVideonews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('videoPublicId', models.CharField(max_length=1000)),
                ('videoUrl', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
