# Generated by Django 3.1.7 on 2022-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entertainmentNewsdb_for_aajtk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('nextrandom', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='entertainmentSaveVideonews_for_aajtk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('videoPublicId', models.CharField(max_length=1000)),
                ('videoUrl', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
