# Generated by Django 3.1.7 on 2021-03-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_auto_20210304_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentdb',
            name='nextrandom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
