# Generated by Django 3.1.7 on 2021-05-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_savevideo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='savevideo',
            name='nameofvideo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
