# Generated by Django 3.1.7 on 2021-05-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0009_savevideo_nameofvideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveVideo',
            new_name='SaveVideo_entertainment',
        ),
        migrations.DeleteModel(
            name='entertainmentdb',
        ),
    ]
